// <auto-generated />
namespace MVC_ArsonProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class UpdateModelMemberServiceUnit2StartYear2etc : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UpdateModelMemberServiceUnit2StartYear2etc));
        
        string IMigrationMetadata.Id
        {
            get { return "202309081812090_Update Model Member ServiceUnit2 StartYear2 etc."; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
