// <auto-generated />
namespace MVC_ArsonProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class createModelNews : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createModelNews));
        
        string IMigrationMetadata.Id
        {
            get { return "202309230248334_create Model News"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
